### ISSUE TITLE
made infinite copies of bookgen collection when i moved bookgen collection into another collection by dragging into another collection.

### ISSUE THREAD

**Issue by arcdipesh** [oweissbarth/bookGen#17]
you can open a file make your collection bbokgen will create a collection in scene collection ,,if you want bookgn collection into another collection and drag bookgen collection into your other collection it will create infinite copies of collection inside it.if u are in the middle of important project t
![image](https://user-images.githubusercontent.com/50439654/104622259-22efa000-56b9-11eb-8b9d-cbf7826ae4c4.png)
hen u will ruin your whole project with so many collections.

**Comment by oweissbarth** [comment]
@arcdipesh
Can you please test the release candidate (https://github.com/oweissbarth/bookGen/releases/tag/1.0.1_RC1) and see if it fixes your issue? There is also a script that removes the additional collections if you need that.
Thanks for your help.
