### ISSUE TITLE
BookGen Outliner Issue

### ISSUE THREAD

**Issue by PixalateSketch** [oweissbarth/bookGen#18]
I just noticed that a BookGen collection is being created every time I open the properties panel -N-. Regardless of what object I have selected or anything. As long as the panel is open, I can't delete the collection. If It's closed, I can, but then it reappears when I open the panel.

**Comment by izzy** [comment]
This is even worse when you move the collection into another one. It will immediatly start to generate collections called BookGen.NNN - I've had them up into the tens of thousands when I started noticing that my blender slowed down dramatically. There's no easy way to remove all those collections fast and if you can't find the original BookGen collection... Well, hope you have backups or didn't save after moving the collection. No way of Ctrl-Z'ing your way out of this.

Idk about you but for me this isn't just an enhancement but an actual bug that can *really* fuck you over if you're not careful. Using BookGen after this happened to me feels like having a plutonium next to the salt in the kitchen...

**Comment by oweissbarth** [comment]
@izzy The issue that is tracked here is the unnecessary creation of a "bookGen"-collection when bookGen is not used. This is not nice but does no harm either -> enhancement.
The issue you are describing is a bug that is being tracked here: https://github.com/oweissbarth/bookGen/issues/17
I will fix both issues. I just need to find the time to do it.

**Comment by oweissbarth** [comment]
This was fixed in 6bf8529846f1919734683a7580fc26b748e68588 and  95457023bd6e7cf6d6ef697b15190a66499dd12d
The fix will be included in the next minor release that will be published shortly.
@PixalateSketch thanks for reporting!
