### ISSUE TITLE
Infinite recursion BUG

### ISSUE THREAD

**Issue by 1234EMMM** [oweissbarth/bookGen#21]
If I click on the complete copy scene, then bookGen will recursively copy an infinite number of collections

如果我点击了完整复制场景,那么bookGen就会无限递归,复制出无限个集合出来
![image](https://user-images.githubusercontent.com/49475772/120920898-bb7fce80-c6f3-11eb-8c83-2c8c592efbfc.png)
![image](https://user-images.githubusercontent.com/49475772/120920900-bc186500-c6f3-11eb-9275-b4c0509c60e8.png)

**Comment by oweissbarth** [comment]
Hi @1234EMMM,
Thanks for the report. What version of bookGen  and Blender are you using?
Thanks for your support.
Oliver

**Comment by oweissbarth** [comment]
Closing as there was no response for 20 days. Feel free to reopen it or create a new ticket if the issue persists.

**Comment by 1234EMMM** [comment]
@oweissbarth 
Oh, sorry for taking so long to reply. I use version 2.93 blender
哦，报歉这么久才回复，我是使用的2.93版本的blender

**Comment by oweissbarth** [comment]
@1234EMMM 
Which version of bookGen do you use?

**Comment by 1234EMMM** [comment]
@oweissbarth Oh, I've just tried the latest version and there's no problem, but if you create a new scene, it will still be generated in the original scene. I guess this is a new bug
哦，我刚刚试了最新的版本，没有这个问题了，但是如果创建一个新的场景的话，还是会生成在原场景哦，我猜这是一个新的bug

**Comment by 1234EMMM** [comment]
I just tried version 1.01. There is no such problem
