### ISSUE TITLE
Multiple Books

### ISSUE THREAD

**Issue by PixalateSketch** [oweissbarth/bookGen#22]
I'm not sure if I'm doing something wrong but when I try to make more than one set of books and then try to change settings, both books change and and get in the same place. If I create a new settings thing, the same happens except one of the sets may not move but the other is kinda teleported to it.

**Comment by oweissbarth** [comment]
Hi @PixalateSketch,
thank you for your interest in bookGen.
There are two things to keep in mind:
1.  When you change properties of a setting all grouping that use that setting will be effected. By default all grouping you create use the same setting. If you want to change that you have to click on the plus sign next to "BookGenSettings" and create a new set of settings.
2. After you created a grouping the grouping cannot be moved or duplicated (they remember the original position they were created in). If you want more shelves or stacks use the "Add Shelf" or "Add Stack" button.

I hope this helps. If you are still having problem or need further assistance let me know.

Have a nice day.

Oliver

**Comment by oweissbarth** [comment]
Closing as there was no response for 30 days. Feel free to reopen it or create a new ticket if the issue persists.
