### ISSUE TITLE
Cannot enable addon

### ISSUE THREAD

**Issue by Pixelluca** [oweissbarth/bookGen#23]
I'm using bookgen version 1.0.2, the latest version from the linked website. I'm running blender 3.5.0. Whenever I try to enable the addon, I get the following error:
```
Traceback (most recent call last):
	File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py" line 333, in enable
		mod = __import__(module_name)
	File "C:Users\mypc\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\bookGen\__init__.py", line 25, in <module>
		from .properties import BookGenProperties, BookGenGroupingProperties, BookGenAddonProperties
	File "C:Users\mypc\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\bookGen\properties.py", line 21, in <module>
		from utils (import
	ImportError: cannot import name 'get_bookgen_collection' from 'bookgen.utils' (C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py)
```

**Comment by oweissbarth** [comment]
Hi @Pixelluca,
I tested this using the same version of blender and the same add-on version on Windows. Unfortunately, I unable to reproduce your problem.
However I noticed the excerpts from the code that are part of the error message do not match the official release.
You can try the following: 
- Uninstall the add-on and close Blender
- Download a fresh copy of the add-on from https://ow3d.de/bookGen
- Restart Blender and install the newly downloaded version.
- Try to activate it

Please let me know if this works for you.

**Comment by Pixelluca** [comment]
Thanks for getting back to me! I followed your steps, and the plugin works now. Thank you for the help!
