### ISSUE TITLE
"Add Shelf" not working in Blender 3.6 or 4.0 on OSX Monterey 12.6 (M1)

### ISSUE THREAD

**Issue by charlielaud** [oweissbarth/bookGen#25]
Add Stack seems to work just fine but Add Shelf throws this error.

```
Python: Traceback (most recent call last):
  File "/Users/userxyz/Library/Application Support/Blender/3.6/scripts/addons/bookGen/shelf_operator.py", line 219, in invoke
    self.gizmo = BookGenShelfGizmo(props["book_height"], props["book_depth"], context)
  File "/Users/userxyz/Library/Application Support/Blender/3.6/scripts/addons/bookGen/ui_gizmo.py", line 35, in __init__
    self.line_shader = gpu.types.GPUShader(vertex_shader, fragment_shader)
Exception: Shader Compile Error, see console for more details
```

**Comment by oweissbarth** [comment]
Hi @charlielaud,
Thanks for reporting the issue. I will investigate and get back to you.

**Comment by charlielaud** [comment]
Ah, I should add - this was with the build that's available on your website. (version 1.0.3) . Let me know if I should try using the most recent version hosted here (saw the request to use the website version instead of the most recent repo).
And thanks for taking a look! This is a really cool add-on and I'm excited to mess around with it. Appreciate your work!

**Comment by oweissbarth** [comment]
Hi @charlielaud,
I have created an updated version. Could you test this and let me know if this fixes your issue?
Thanks in advance for your help!
[bookGen_1_0_3_a.zip](https://github.com/oweissbarth/bookGen/files/14396844/bookGen_1_0_3_a.zip)

**Comment by charlielaud** [comment]
Thanks for looking into it! Did a clean install but unfortunately I'm getting a similar error:

```
Python: Traceback (most recent call last):
  File "/Users/UserXYZ/Library/Application Support/Blender/4.0/scripts/addons/bookGen/shelf_operator.py", line 219, in invoke
    self.gizmo = BookGenShelfGizmo(props["book_height"], props["book_depth"], context)
  File "/Users/UserXYZ/Library/Application Support/Blender/4.0/scripts/addons/bookGen/ui_gizmo.py", line 35, in __init__
    line_shader_info = GPUShaderCreateInfo()
Exception: Shader Compile Error, see console for more details
```

**Comment by oweissbarth** [comment]
Hi @charlielaud,
i have retested this on to M1 Macs. One with 14.3 (Sonoma) and one with 13.6 (Ventura). I was unable to reproduce your issue.
Could you try to run Blender from the command line to get potentially more information about the error?
Open the Terminal app and running the following command:
`/Applications/Blender.app/Contents/MacOS/Blender`
Than try to add a shelf. Then copy the entire content of the terminal window and paste it to this ticket.


Also is there something special about your setup? Is an official blender version from blender.org? 

Thanks in advance for your help.

**Comment by charlielaud** [comment]
Well now I can't recreate the issue either! Started Blender from command line and BookGen (1.0.3.a) worked just fine. Re-tried by starting Blender (4.0.2) from the dock and it also worked.

For historical context, I'd just updated Blender from 3.8 to 4.0.2 so my best guess is that some wonky setting information carried over, which was fixed by a reboot. Just a guess though.

Thanks for your help on this, this add-on rules!

**Comment by charlielaud** [comment]
Well now I can't recreate the issue either! Started Blender from command line and BookGen (1.0.3.a) worked just fine. Re-tried by starting Blender (4.0.2) from the dock and it also worked.

For historical context, I'd just updated Blender from 3.8 to 4.0.2 so my best guess is that some wonky setting information carried over, which was fixed by a reboot. Just a guess though.

Thanks for your help on this, this add-on rules!
