### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by vaggss** [oweissbarth/bookGen#26]
![image](https://github.com/user-attachments/assets/8f202262-535a-4ae7-be2d-38db6c81a2ae)

**Comment by oweissbarth** [comment]
Hi @vaggss,
you using Blender 3.1 which is not supported anymore. The add-on currently supports:
- Blender 3.3 LTS
- Blender 3.6 LTS
- Blender 4.0
- Blender 4.1
Please update Blender to one of the supported versions.
I am working on supporting Blender 4.2 (https://github.com/oweissbarth/bookGen/issues/27)
