### ISSUE TITLE
an update for Blender 2.8 ?

### ISSUE THREAD

**Issue by xan2622** [oweissbarth/bookGen#7]
Hi

Would it be possible to get an updated version of BookGen for Blender 2.8 ?

Your addon deserves to be listed at https://blenderartists.org/t/list-of-addons-that-work-with-2-8/1132912 :)

Thank you.

**Comment by oweissbarth** [comment]
Thanks for your interest in bookGen. I am working on updating bookGen for Blender 2.8. The update to 2.8 will also include some new features. Some code is already available in the 2.8 branch. I hope to get it done before the 2.8 release.

**Comment by xan2622** [comment]
What kind of new features? This is intriguing ;-) 
A random inclination generator that could tilt some books on the other well-aligned books ?

![shelf-159852_960_720](https://user-images.githubusercontent.com/1732773/60772333-246bff80-a0f5-11e9-8a74-bc558cb456ba.png)

**Comment by oweissbarth** [comment]
@xan2622 Are you a mind reader? ;)

**Comment by xan2622** [comment]
Hehe, no but that seemed like the most logical feature to add into your addon. :)

You said that you hoped to get it done before the 2.8 release, it sounds difficult to implement, isn't it? 
How complete is this feature in its development?

**Comment by oweissbarth** [comment]
The leaning part is fully implemented. I want to update the model to make it a bit more light. This will take some time due to the parametric nature of the model.

**Comment by oweissbarth** [comment]
bookGen 0.9.0 with support for Blender 2.8x is released.
